### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by duk242** [danozdotnet/netupmon#3]
To make it work on OSX:
Add this to the detect OS thingy:

```
    darwin*)
      OS="darwin";
      [[ "$FPING" ]] && PING="fping -c 1 -t $TIMEOUT -u -q" || PING="ping -c1 -t1";; 
```

here's the OSTYPE if you need it:

```
[duck@Adria] Scripts$ echo $OSTYPE
darwin15
```

Also for the date in the ConvertDATE function: 
`[[ "$OS" == "darwin" ]] && printf "%s" "$(date -r "$1" +"%d/%m/%Y %H:%M:%S")"`
(the date command is the same as the BSD one)

fping detection is broken too. 

```
[duck@Adria] Scripts$ type fping 2>/dev/null 2>&1
fping is hashed (/opt/local/sbin/fping)
[duck@Adria] Scripts$ type fping2 >/dev/null 2>&1
[duck@Adria] Scripts$
```

Changing the line: `FPING=$(type fping 2>/dev/null 2>&1)`
to: `FPING=$(type fobviouslywrongping 2>/dev/null 2>&1)`
to make it fail, it still seems to return true. For now I'm running it in ping only mode.

**Comment by danozdotnet** [comment]
osx support added, fping issue handled by other ticket (#2)
